version: '3.8'

services:

  db:
    image: postgres
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
    environment:
      POSTGRES_DB: furniture_shop
      POSTGRES_USER: app_admin
      POSTGRES_PASSWORD: admin1234
    ports:
      - 2205:5432
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local